package reservation.donnes;
// Generated 2014-08-05 12:13:05 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Chambre generated by hbm2java
 */
public class Chambre  implements java.io.Serializable {


     private Integer numero;
     private Set reservations = new HashSet(0);

    public Chambre() {
    }

    public Chambre(Set reservations) {
       this.reservations = reservations;
    }
   
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


