package reservation.donnes;
// Generated 2014-08-05 12:13:05 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Client generated by hbm2java
 */
public class Client  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String prenom;
     private Set reservations = new HashSet(0);

    public Client() {
    }

	
    public Client(String prenom) {
        this.prenom = prenom;
    }
    public Client(String nom, String prenom, Set reservations) {
       this.nom = nom;
       this.prenom = prenom;
       this.reservations = reservations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


