package reservation.donnes;
// Generated 2014-08-05 12:13:05 by Hibernate Tools 3.6.0



/**
 * ReservationId generated by hbm2java
 */
public class ReservationId  implements java.io.Serializable {


     private int idReservation;
     private int numero;

    public ReservationId() {
    }

    public ReservationId(int idReservation, int numero) {
       this.idReservation = idReservation;
       this.numero = numero;
    }
   
    public int getIdReservation() {
        return this.idReservation;
    }
    
    public void setIdReservation(int idReservation) {
        this.idReservation = idReservation;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ReservationId) ) return false;
		 ReservationId castOther = ( ReservationId ) other; 
         
		 return (this.getIdReservation()==castOther.getIdReservation())
 && (this.getNumero()==castOther.getNumero());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdReservation();
         result = 37 * result + this.getNumero();
         return result;
   }   


}


