package reservation.donnes;
// Generated 2014-08-05 12:13:05 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Reservation generated by hbm2java
 */
public class Reservation  implements java.io.Serializable {


     private ReservationId id;
     private Chambre chambre;
     private Client client;
     private Date arrivee;
     private Integer sejour;
     private Date dateCreation;

    public Reservation() {
    }

	
    public Reservation(ReservationId id, Chambre chambre) {
        this.id = id;
        this.chambre = chambre;
    }
    public Reservation(ReservationId id, Chambre chambre, Client client, Date arrivee, Integer sejour, Date dateCreation) {
       this.id = id;
       this.chambre = chambre;
       this.client = client;
       this.arrivee = arrivee;
       this.sejour = sejour;
       this.dateCreation = dateCreation;
    }
   
    public ReservationId getId() {
        return this.id;
    }
    
    public void setId(ReservationId id) {
        this.id = id;
    }
    public Chambre getChambre() {
        return this.chambre;
    }
    
    public void setChambre(Chambre chambre) {
        this.chambre = chambre;
    }
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }
    public Date getArrivee() {
        return this.arrivee;
    }
    
    public void setArrivee(Date arrivee) {
        this.arrivee = arrivee;
    }
    public Integer getSejour() {
        return this.sejour;
    }
    
    public void setSejour(Integer sejour) {
        this.sejour = sejour;
    }
    public Date getDateCreation() {
        return this.dateCreation;
    }
    
    public void setDateCreation(Date dateCreation) {
        this.dateCreation = dateCreation;
    }




}


